apiVersion: v1
kind: ServiceAccount

metadata:
  name: securekube-readonly
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: securekube-pod-reader
  namespace: default

rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: securekube-readonly-binding
  namespace: default

subjects:
  - kind: ServiceAccount
    name: securekube-readonly
    namespace: default

roleRef:
  kind: Role
  name: securekube-pod-reader
  apiGroup: rbac.authorization.k8s.io